image: alpine

# before_script:
#   - mkdir -p $HOME/.docker/
#   - 'echo "{ \"proxies\": { \"default\": { \"httpProxy\": \"http://proxy-us.intel.com:911\", \"httpsProxy\": \"http://proxy-us.intel.com:912\", \"noProxy\": \"intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16\" } } }" > $HOME/.docker/config.json'

pages:

  script:
  - export http_proxy=http://proxy-us.intel.com:911
  - export https_proxy=http://proxy-us.intel.com:912
  - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx sphinx_rtd_theme sphinxcontrib.napoleon
  - pip install numpy pyyaml
  
  - apk --no-cache add make
  - cd docs
  - sphinx-apidoc -f -o . ../tfedlrn
  - make html
  - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
