# CLEANUP FOR FLEDGE

stages:
    - build
    - test
    
pages:
  stage: build
  tags:
  - alpine-runner-sh-1
  image: python:3.7-alpine
  script:
  - export http_proxy=http://proxy-us.intel.com:911
  - export https_proxy=http://proxy-us.intel.com:912
  - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16

  - apk --no-cache add make
  - apk --no-cache --update-cache add gcc gfortran build-base wget freetype-dev libpng-dev openblas-dev  zlib-dev jpeg-dev
  - pip install numpy pyyaml nibabel tqdm pillow
  - pip install sphinx sphinx_rtd_theme sphinxcontrib.napoleon recommonmark numpy pyyaml nibabel tqdm rinohtype Sphinx-Substitution-Extensions

  - cd docs
  - make html
  - mv _build/html/ ../public/
  - mv _build/rinoh/ ../public/pdf/

  artifacts:
    paths:
    - public
  only:
  - master

test_spsm_gpu:
    stage: test
    tags:
    - docker-gpu
    image: docker-gpu:v3
    before_script:
    #- cd /home/testuser/tfl
    - whoami
    - pwd
    - nvidia-smi
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    #- apt-get update -qy
    #- apt-get install -y python3-venv python3-pip build-essential musl-dev g++
    - python3 -m pip --version
    - echo 'modifying setup.py for tensorflow-gpu'
    - sed -i -e 's/tensorflow==/tensorflow-gpu==/g' setup.py
    - make clean
    - make install
    - ./venv/bin/python3 -m pip --version
    script:
    - cd test_fl/
    - ./test_spsm_gpu.sh
    timeout: 10m
    when: manual

test_spsm_cpu:
    stage: test
    tags:
    - sdp-cpu-runner2
    #- shell-runner-1
    before_script:
    - whoami
    - pwd
    - ls -al
    - cd /home/gitlab-runner/workspace/tmp_spsm_cpu
    - echo "remove the directory ..."
    - rm -rf spr_secure_intelligence-trusted_federated_learning
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/tmp_spsm_cpu/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    #- apt-get update -qy
    #- apt-get install -y python3-venv python3-pip build-essential musl-dev g++
    - make clean
    - make install
    - ./venv/bin/python3 -m pip --version
    script:
    - cd test_fl/
    - ./test_spsm.sh
    timeout: 5h 30m
    when: manual

test_spsm_cpu_compression:
    stage: test
    tags:
    - shell-runner-1
    #- alpine-runner-sh-1
    before_script:
    - whoami
    - pwd
    - ls -al
    - cd /home/gitlab-runner/workspace/tmp_spsm_cpu_compression
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/tmp_spsm_cpu_compression/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - python3 -m pip --version
    - make clean
    - make install
    - ./venv/bin/python3 -m pip --version
    script:
    - cd test_fl/
    - ./test_spsm_compression.sh
    timeout: 5h 30m
    when: manual

test_mpsm_shell_1:
    stage: test
    tags:
    - shell-runner-1
    before_script:
    - whoami
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace/tmp_mpsm
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/tmp_mpsm/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - python3 -m pip --version
    - make clean
    - make install
    - rm -rf ./bin/federations/certs
    - echo "copy the certs ..."
    - cp -r /home/gitlab-runner/workspace/pki ./bin/federations/
    - echo "copy the network.yaml file ..."
    - cp -r /home/gitlab-runner/workspace/plan_defaults/network.yaml ./bin/federations/plans/defaults/
    script:
    - cd test_fl/
    - ./test_mpsm.sh
    timeout: 20m
    when: manual
    after_script:
    - jobs
    - echo "cleaning ...... $$"
    - kill -15 $$

test_mpmm_shell_1:
    stage: test
    tags:
    - shell-runner-1
    before_script:
    - whoami
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge 
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - python3 -m pip --version
    - make clean
    - make install
    - rm -rf ./bin/federations/pki
    - echo "copy the certs ..."
    - cp -r /home/gitlab-runner/workspace/pki ./bin/federations/
    - echo "copy the network.yaml file ..."
    - cp -r /home/gitlab-runner/workspace/plan_defaults/network.yaml ./bin/federations/plans/defaults/
    script:
    - cd test_fl/
    - ./test_mpmm_gpu01.sh
    timeout: 20m
    when: manual
    after_script:
    - jobs
    - echo "cleaning ...... $$"
    - kill -15 $$

test_mpmm_shell_2:
    stage: test
    tags:
    - shell-runner-2
    before_script:
    - whoami
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - python3 -m pip --version
    - make clean
    - make install
    - rm -rf ./bin/federations/certs
    - echo "copy the certs ..."
    - cp -r /home/gitlab-runner/workspace/pki ./bin/federations/
    - echo "copy the network.yaml file ..."
    - cp -r /home/gitlab-runner/workspace/plan_defaults/network.yaml ./bin/federations/plans/defaults/
    script:
    - cd test_fl/
    - ./test_mpmm_gpu02.sh
    timeout: 20m
    when: manual
    after_script:
    - jobs
    - echo "cleaning ...... $$"
    - kill -15 $$

hello_federation:
    stage: test
    tags:
    - shell-runner-2
    before_script:
    - whoami
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - export FQDN=$(hostname --all-fqdns | awk '{print $1}')
    - python3 -m pip install --user --upgrade pip
    script:
    - python3 -m pip install . --user
    - fx workspace create --prefix /home/gitlab-runner/workspace --template keras_cnn_mnist
    - cd /home/gitlab-runner/workspace
    - fx workspace certify
    - fx aggregator certify
    - fx collaborator certify -n one
    - fx collaborator certify -n two
    - fx plan initialize
    - fx aggregator start &
    - fx collaborator start -n one &
    - fx collaborator start -n two
    after_script:
    - jobs
    - echo "cleaning ...... $$"
    - kill -15 $$
