# CLEANUP FOR FLEDGE

stages:
    - build
    - test
    
pages:
  stage: build
  tags:
  - alpine-runner-sh-1
  image: python:3.7-alpine
  script:
  - export http_proxy=http://proxy-us.intel.com:911
  - export https_proxy=http://proxy-us.intel.com:912
  - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16

  - apk --no-cache add make
  - apk --no-cache --update-cache add gcc gfortran build-base wget freetype-dev libpng-dev openblas-dev  zlib-dev jpeg-dev
  - pip install numpy pyyaml nibabel tqdm pillow
  - pip install sphinx sphinx_rtd_theme sphinxcontrib.napoleon recommonmark numpy pyyaml nibabel tqdm rinohtype Sphinx-Substitution-Extensions

  - cd docs
  - make html
  - mv _build/html/ ../public/
  - mv _build/rinoh/ ../public/pdf/

  artifacts:
    paths:
    - public
  only:
  - master

hello_federation_keras:
    stage: test
    tags:
    - shell-runner-2
    before_script:
    - whoami
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - export FQDN=$(hostname --all-fqdns | awk '{print $1}')
    - export COL1=Alpha32T
    - export COL2=beTA816r4
    - python3 -m pip install --user --upgrade pip
    - python3 -m pip install --user intel-tensorflow==1.15.2
    script:
    - python3 -m pip install . --user
    - /home/gitlab-runner/workspace/fledge/tests/gitlab/test_hello_federation.sh keras_cnn_mnist workspace_keras ${COL1} ${COL2}
    after_script:
    - jobs
    - echo "cleaning ...... $$"
    - kill -15 $$

hello_federation_pytorch:
  stage: test
  tags:
  - shell-runner-2
  before_script:
  - whoami
  - pwd
  - ls
  - cd /home/gitlab-runner/workspace
  - echo "remove the directory ..."
  - rm -rf fledge
  - echo "clone the directory ..."
  - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
  - cd /home/gitlab-runner/workspace/fledge
  - echo $CI_COMMIT_REF_NAME
  - git checkout $CI_COMMIT_REF_NAME
  - export http_proxy=http://proxy-us.intel.com:911
  - export https_proxy=http://proxy-us.intel.com:912
  - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
  - export FQDN=$(hostname --all-fqdns | awk '{print $1}')
  - export COL1=one23
  - export COL2=two34
  - python3 -m pip install --user --upgrade pip
  - python3 -m pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  script:
    - python3 -m pip install . --user
    - /home/gitlab-runner/workspace/fledge/tests/gitlab/test_hello_federation.sh torch_cnn_mnist workspace_torch ${COL1} ${COL2}
  after_script:
  - jobs
  - echo "cleaning ...... $$"
  - kill -15 $$
