
#image: alpine
# before_script:
#   - mkdir -p $HOME/.docker/
#   - 'echo "{ \"proxies\": { \"default\": { \"httpProxy\": \"http://proxy-us.intel.com:911\", \"httpsProxy\": \"http://proxy-us.intel.com:912\", \"noProxy\": \"intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16\" } } }" > $HOME/.docker/config.json'
stages:
    - build
    - test

pages:
  stage: build
  tags: 
  - alpine-runner-sh-1
  image: alpine
  script:
  - export http_proxy=http://proxy-us.intel.com:911
  - export https_proxy=http://proxy-us.intel.com:912
  - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
  - apk --no-cache add py3-pip python3-dev
  - apk --no-cache add musl-dev linux-headers g++

  - pip3 install sphinx sphinx_rtd_theme sphinxcontrib.napoleon
  - pip3 install numpy pyyaml
  - pip3 install protobuf
  
  - apk --no-cache add make
  - cd docs
  - sphinx-apidoc -f -o . ../tfedlrn
  - sphinx-apidoc -f -o . ../models
  - make html
  - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master

test_spsm_gpu:
    stage: test
    tags: 
    - docker-gpu
    image: docker-gpu:v3
    before_script:
    #- cd /home/testuser/tfl
    - whoami
    - pwd
    - nvidia-smi
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    #- apt-get update -qy
    #- apt-get install -y python3-venv python3-pip build-essential musl-dev g++
    - python3 -m pip --version
    - echo 'modifying setup.py for tensorflow-gpu'
    - sed -i -e 's/tensorflow==/tensorflow-gpu==/g' setup.py
    - make clean
    - make install
    - ./venv/bin/python3 -m pip --version
    script: 
    - cd test_fl/
    - ./test_spsm_gpu.sh
    timeout: 10m
    when: manual

test_spsm_cpu:
    stage: test
    tags: 
    - sdp-cpu-runner1
    #- shell-runner-1
    before_script:
    - whoami
    - pwd
    - ls -al 
    - cd /home/gitlab-runner/workspace/tmp_spsm_cpu
    - echo "remove the directory ..."
    - rm -rf spr_secure_intelligence-trusted_federated_learning
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/spr_secure_intelligence-trusted_federated_learning.git
    - cd /home/gitlab-runner/workspace/tmp_spsm_cpu/spr_secure_intelligence-trusted_federated_learning
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - python3 -m pip --version
    #- apt-get update -qy
    #- apt-get install -y python3-venv python3-pip build-essential musl-dev g++
    - make clean
    - make install
    - ./venv/bin/python3 -m pip --version
    script: 
    - cd test_fl/
    - ./test_spsm.sh
    timeout: 5h 30m
    when: manual

test_mpsm_shell_1:
    stage: test 
    tags: 
    - shell-runner-1
    before_script:
    - whoami
    - pwd 
    - ls
    - cd /home/gitlab-runner/workspace/tmp_mpsm
    - echo "remove the directory ..."
    - rm -rf spr_secure_intelligence-trusted_federated_learning
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/spr_secure_intelligence-trusted_federated_learning.git
    - cd /home/gitlab-runner/workspace/tmp_mpsm/spr_secure_intelligence-trusted_federated_learning
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - python3 -m pip --version
    - make clean
    - make install
    - rm -rf ./bin/federations/certs
    - echo "copy the certs ..."
    - cp -r /home/gitlab-runner/workspace/pki ./bin/federations/
    script:
    - cd test_fl/
    - ./test_mpsm.sh
    timeout: 20m
    when: manual
    after_script:
    - jobs
    - echo "cleaning ...... $$"
    - kill -15 $$

test_mpmm_shell_1:
    stage: test
    tags: 
    - shell-runner-1
    before_script:
    - whoami
    - pwd 
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf spr_secure_intelligence-trusted_federated_learning
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/spr_secure_intelligence-trusted_federated_learning.git
    - cd /home/gitlab-runner/workspace/spr_secure_intelligence-trusted_federated_learning
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - python3 -m pip --version
    - make clean
    - make install
    - rm -rf ./bin/federations/pki
    - echo "copy the certs ..."
    - cp -r /home/gitlab-runner/workspace/pki ./bin/federations/
    script:
    - cd test_fl/
    - ./test_mpmm_gpu01.sh
    timeout: 20m
    when: manual
    after_script:
    - jobs
    - echo "cleaning ...... $$"
    - kill -15 $$

test_mpmm_shell_2:
    stage: test
    tags: 
    - shell-runner-2
    before_script:
    - whoami
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf spr_secure_intelligence-trusted_federated_learning
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/spr_secure_intelligence-trusted_federated_learning.git
    - cd /home/gitlab-runner/workspace/spr_secure_intelligence-trusted_federated_learning
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - python3 -m pip --version
    - make clean
    - make install
    - rm -rf ./bin/federations/certs
    - echo "copy the certs ..."
    - cp -r /home/gitlab-runner/workspace/pki ./bin/federations/
    script:
    - cd test_fl/
    - ./test_mpmm_gpu02.sh
    timeout: 20m
    when: manual
    after_script:
    - jobs
    - echo "cleaning ...... $$"
    - kill -15 $$

