stages:
  - pep8
  - unit-tests
  - build
  - test

pages:
  stage: build
  tags:
    - alpine-runner-sh-1
  image: python:3.6-alpine
  script:
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16

    - apk --no-cache add make
    - apk --no-cache --update-cache add gcc gfortran build-base wget freetype-dev libpng-dev openblas-dev  zlib-dev jpeg-dev
    - pip install numpy pyyaml nibabel tqdm pillow
    - pip install sphinx sphinx_rtd_theme sphinxcontrib.napoleon recommonmark numpy pyyaml nibabel tqdm rinohtype Sphinx-Substitution-Extensions sphinxcontrib-mermaid

    - cd docs
    - make html
    - mv _build/html/ ../public/
    - mv _build/rinoh/ ../public/pdf/

    - cd ..
    - mkdir -p public/packages
    - python3 setup.py sdist bdist_wheel
    - mv dist/fledge*.whl public/packages/
  artifacts:
    paths:
      - public
  only:
    - master

pep8:
  stage: pep8
  tags:
    - charlie
  before_script:
    - whoami
    - echo "Killing running fledge processes..." && if pgrep fx; then pkill fx; fi
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - pip install --user --upgrade pip
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate
  script:
    - pip install -r requirements-linters.txt
    - flake8 --extend-exclude .venv
  after_script:
    - deactivate && rm -rf .venv

unit-tests:
  stage: unit-tests
  tags:
    - charlie
  before_script:
    - whoami
    - echo "Killing running fledge processes..." && if pgrep fx; then pkill fx; fi
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - python3 -m venv venv
    - pip install --user --upgrade pip
  script:
    - pip install -r requirements-test.txt --user
    - pytest
  after_script:
    - deactivate && rm -rf venv

keras_cnn_mnist:
  stage: test
  tags:
    - charlie
  before_script:
    - whoami
    - echo "Killing running fledge processes..." && if pgrep fx; then pkill fx; fi
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - export FQDN=$(hostname --all-fqdns | awk '{print $1}')
    - export COL1=alpha32tr
    - export COL2=beta816r4
    - export FED_WORKSPACE=keras_cnn_mnist
    - export FED_DIRECTORY=workspace_keras
    - python3 -m venv venv
    - pip install --user --upgrade pip
  script:
    - pip install . --user
    - /home/gitlab-runner/workspace/fledge/tests/gitlab/test_hello_federation.sh ${FED_WORKSPACE} ${FED_DIRECTORY}} ${COL1} ${COL2} --rounds-to-train 3
  after_script:
    - jobs
    - echo "cleaning ...... $$"
    - deactivate && rm -rf venv
    - kill -15 $$

torch_cnn_mnist:
  stage: test
  tags:
   - charlie
  before_script:
    - whoami
    - echo "Killing running fledge processes..." && if pgrep fx; then pkill fx; fi
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - export FQDN=$(hostname --all-fqdns | awk '{print $1}')
    - export COL1=one23
    - export COL2=two34
    - export FED_WORKSPACE=torch_cnn_mnist
    - export FED_DIRECTORY=workspace_torch
    - python3 -m venv venv
    - pip install --user --upgrade pip
  script:
    - pip install . --user
    - /home/gitlab-runner/workspace/fledge/tests/gitlab/test_hello_federation.sh ${FED_WORKSPACE} ${FED_DIRECTORY} ${COL1} ${COL2} --rounds-to-train 3
  after_script:
    - jobs
    - echo "cleaning ...... $$"
    - deactivate && rm -rf venv
    - kill -15 $$

fe_tf_adversarial_cifar:
  stage: test
  tags:
   - charlie
  before_script:
    - whoami
    - echo "Killing running fledge processes..." && if pgrep fx; then pkill fx; fi
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - export FQDN=$(hostname --all-fqdns | awk '{print $1}')
    - export COL1=one23
    - export COL2=two34
    - export FED_WORKSPACE=fe_tf_adversarial_cifar
    - export FED_DIRECTORY=workspace_fe_tf_adversarial_cifar
    - python3 -m pip install --user --upgrade pip
  script:
    - python3 -m pip install . --user
    - /home/gitlab-runner/workspace/fledge/tests/gitlab/test_hello_federation.sh ${FED_WORKSPACE} ${FED_DIRECTORY} ${COL1} ${COL2} --rounds-to-train 3
  after_script:
    - jobs
    - echo "cleaning ...... $$"
    - kill -15 $$

fe_torch_adversarial_cifar:
  stage: test
  tags:
   - charlie
  before_script:
    - whoami
    - echo "Killing running fledge processes..." && if pgrep fx; then pkill fx; fi
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - export FQDN=$(hostname --all-fqdns | awk '{print $1}')
    - export COL1=one23
    - export COL2=two34
    - export FED_WORKSPACE=fe_torch_adversarial_cifar
    - export FED_DIRECTORY=workspace_fe_torch_adversarial_cifar
    - python3 -m venv venv
    - pip install --user --upgrade pip
  script:
    - pip install . --user
    - /home/gitlab-runner/workspace/fledge/tests/gitlab/test_hello_federation.sh ${FED_WORKSPACE} ${FED_DIRECTORY} ${COL1} ${COL2} --rounds-to-train 3
  after_script:
    - jobs
    - echo "cleaning ...... $$"
    - deactivate && rm -rf venv
    - kill -15 $$

torch_cnn_histology:
  stage: test
  tags:
   - charlie
  before_script:
    - whoami
    - echo "Killing running fledge processes..." && if pgrep fx; then pkill fx; fi
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - export FQDN=$(hostname --all-fqdns | awk '{print $1}')
    - export COL1=one23
    - export COL2=two34
    - export FED_WORKSPACE=torch_cnn_histology
    - export FED_DIRECTORY=workspace_torch_cnn_histology
    - python3 -m venv venv
    - pip install --user --upgrade pip
  script:
    - pip install . --user
    - /home/gitlab-runner/workspace/fledge/tests/gitlab/test_hello_federation.sh ${FED_WORKSPACE} ${FED_DIRECTORY} ${COL1} ${COL2} --rounds-to-train 3
  after_script:
    - jobs
    - echo "cleaning ...... $$"
    - kill -15 $$
    - deactivate && rm -rf venv

tf_cnn_histology:
  stage: test
  tags:
   - charlie
  before_script:
    - whoami
    - echo "Killing running fledge processes..." && if pgrep fx; then pkill fx; fi
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - export FQDN=$(hostname --all-fqdns | awk '{print $1}')
    - export COL1=one23
    - export COL2=two34
    - export FED_WORKSPACE=tf_cnn_histology
    - export FED_DIRECTORY=workspace_tf_cnn_histology
    - python3 -m venv venv
    - pip install --user --upgrade pip
  script:
    - pip install . --user
    - /home/gitlab-runner/workspace/fledge/tests/gitlab/test_hello_federation.sh ${FED_WORKSPACE} ${FED_DIRECTORY} ${COL1} ${COL2} --rounds-to-train 3
  after_script:
    - jobs
    - echo "cleaning ...... $$"
    - kill -15 $$
    - deactivate && rm -rf venv

python_native:
  stage: test
  tags:
   - charlie
  before_script:
    - whoami
    - echo "Killing running fledge processes..." && if pgrep fx; then pkill fx; fi
    - pwd
    - ls
    - cd /home/gitlab-runner/workspace
    - echo "remove the directory ..."
    - rm -rf fledge
    - echo "clone the directory ..."
    - git clone ssh://git@gitlab.devtools.intel.com:29418/secure-intelligence-team/fledge.git
    - cd /home/gitlab-runner/workspace/fledge
    - echo $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - export http_proxy=http://proxy-us.intel.com:911
    - export https_proxy=http://proxy-us.intel.com:912
    - export no_proxy=docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
    - export FQDN=$(hostname --all-fqdns | awk '{print $1}')
    - export COL1=one23
    - export COL2=two34
    - export FED_WORKSPACE=tf_cnn_histology
    - export FED_DIRECTORY=workspace_tf_cnn_histology
    - python3 -m venv venv
    - pip install --user --upgrade pip
  script:
    - pip install . --user
    - python /home/gitlab-runner/workspace/fledge/tests/gitlab/python_native.py
  after_script:
    - jobs
    - echo "cleaning ...... $$"
    - rm -rf ~/.fledge
    - kill -15 $$
    - deactivate && rm -rf venv 
