collaborators:
  col_one_big:
    brats: &brats_data_path '/home/edwardsb/tfl/datasets/brats'
    mnist: &mnist_data_path '/home/edwardsb/tfl/datasets/mnist_batch/mnist_batch.npz'
  col_0:
    brats: *brats_data_path
    mnist: *mnist_data_path
  col_1:
    brats: *brats_data_path
    mnist: *mnist_data_path
  col_2:
    brats: *brats_data_path
    mnist: *mnist_data_path
  col_3:
    brats: *brats_data_path
    mnist: *mnist_data_path
  col_4:
    brats: *brats_data_path
    mnist: *mnist_data_path
  col_5:
    brats: *brats_data_path
    mnist: *mnist_data_path
  col_6:
    brats: *brats_data_path
    mnist: *mnist_data_path
  col_7:
    brats: *brats_data_path
    mnist: *mnist_data_path
  col_8:
    brats: *brats_data_path
    mnist: *mnist_data_path
  col_9:
    brats: *brats_data_path
    mnist: *mnist_data_path
