collaborators:
  col_0:
    data_name: $data_name brats 
    data_path: '/raid/datasets/BraTS17/by_institution_NIfTY/0'
  col_1:
    data_name: *data_name 
    data_path: '/raid/datasets/BraTS17/by_institution_NIfTY/1'
  col_2:
    data_name: *data_name 
    data_path: '/raid/datasets/BraTS17/by_institution_NIfTY/2'
  col_3:
    data_name: *data_name 
    data_path: '/raid/datasets/BraTS17/by_institution_NIfTY/3'
  col_4:
    data_name: *data_name 
    data_path: '/raid/datasets/BraTS17/by_institution_NIfTY/4'
  col_5:
    data_name: *data_name 
    data_path: '/raid/datasets/BraTS17/by_institution_NIfTY/5'
  col_6:
    data_name: *data_name 
    data_path: '/raid/datasets/BraTS17/by_institution_NIfTY/6'
  col_7:
    data_name: *data_name 
    data_path: '/raid/datasets/BraTS17/by_institution_NIfTY/7'
  col_8:
    data_name: *data_name 
    data_path: '/raid/datasets/BraTS17/by_institution_NIfTY/8'
  col_9:
    data_name: *data_name 
    data_path: '/raid/datasets/BraTS17/by_institution_NIfTY/9'
