tasks:
  aggregated_model_validation:
    function  : validate
    kwargs    :
      metrics :
      - f1_score
      - accuracy
      batch_size: 32
  locally_tuned_model_validation:
    function  : validate
    kwargs    :
      metrics :
      - f1_score
      - accuracy
      batch_size: 32
  train:
    function  : train
    kwargs    :
      batch_size: 32
      epochs    : 1.0

task_assigner:
  module_name     : tfedlrn.aggregator.randomgroupedtaskassigner
  class_name      : RandomGroupedTaskAssigner
  task_groups     :
  - name: validation_only
    percentage: 0.7 
    tasks:
    - aggregated_model_validation
  - name: train_and_validate
    percentage: 0.3
    - aggregated_model_validation
    - train
    - locally_tuned_model_validation
