# Compose an FL plan in JSON/YAML.
# * Task name
# * Task description
# * The folder path to the locally runnable code.
# * The software dependency.
# * FL parameters: fed_id, opt_treatment.

# * Added by the coordinator later: agg_id, agg_url, poll_interval.


# We may have several plans for one dataset, to search the best model architecture for exammple.

task            : brats
version         : '1'
description     : Train a model to perform semantic segmentation on brain fMRI images.
status          : active
federation      : fl_brats_2dunet

model:
  name     : brats_2dunet_tensorflow
  code_path: models.brats_2dunet_tensorflow
  version : 1
  params:
    batch_size: 1024
    percent_train: 0.8
    shuffle: True
    dataset_path: ../datasets/brats/

aggregator:
  id             : agg_brats
  addr           : "spr-gpu01.jf.intel.com"
  port           : 8878

  # FIXME: a list of names who are permitted to join the federation. 
  collaborators  : 1
  initial_weights: TensorFlow2DUNet_init.pbuf
  latest_weights : TensorFlow2DUNet_latest.pbuf
  best_weights   : TensorFlow2DUNet_best.pbuf

collaborator:
  opt_vars_treatment : RESET
  sync_per_iterations: 100 

tls:
  disable             : False
  disable_client_auth : False
  cert_folder         : test
