# Compose an FL plan in JSON/YAML.
# * Task name
# * Task description
# * The folder path to the locally runnable code.
# * The software dependency.
# * FL parameters: fed_id, opt_treatment.

# * Added by the coordinator later: agg_id, agg_url, poll_interval.


# We may have several plans for one dataset, to search the best model architecture for exammple.

task            : mnist
version         : 1
description     : Train a model to recognize hand-written digits from 0 to 9.
status          : active
# The federation/plan ID is linked to certain software version, code (including model architecture), initialization, dataset, aggregation configuration, etc.
federation      : fl_mnist_conv2fc2

model:
  name     : mnist_cnn_keras
  optimizer: SGD
  # The code includes pre-processing.
  code_path: models.mnist_cnn_keras
  version : 1
  params:
    # The dataset path will be copy from the dataset section.
    batch_size: 256
    dataset_path: ../datasets/mnist_batch/mnist_batch.npz

aggregator:
  id           : agg_mnist
  addr           : "spr-gpu01.jf.intel.com"
  port           : 8848

  collaborators  : 2
  initial_weights: mnist_cnn_keras_init.pbuf
  latest_weights : mnist_cnn_keras_latest.pbuf
  best_weights   : mnist_cnn_keras_best.pbuf

collaborator:
  # dataset:
  #   # The path in the docker image.
  #   name             : mnist_batch
  #   path             : /opt/datasets/mnist/
  opt_vars_treatment : RESET
  sync_per_iterations: 100 

tls:
  disable             : False
  disable_client_auth : False
  cert_folder         : test
