# Copyright (C) 2020 Intel Corporation
# Licensed subject to the terms of the separately executed evaluation license agreement between Intel Corporation and you.

# Compose an FL plan in YAML
# The plan is consumed by bin/run_simulation_from_flplan.py,
# bin/run_aggregator_from_flplan, bin/run_collaborator_from_flplan, and
# bin/create_initial_weights_file_from_plan.py

aggregator_object_init:
  init_kwargs:
    best_model_fname: pytorch_cnn_best.pbuf
    init_model_fname: pytorch_cnn_init.pbuf
    latest_model_fname: pytorch_cnn_latest.pbuf
    rounds_to_train: 10

collaborator_object_init:
  init_kwargs:
    epochs_per_round: 1.0
    opt_treatment: RESET
    polling_interval: 4
    send_model_deltas: false

data_object_init:
  class_to_init: data.pytorch.ptmnist_inmemory.PyTorchMNISTInMemory
  data_name_in_local_config: mnist_shard
  init_kwargs:
    batch_size: 256
    channels_last: false
    nb_collaborators: 10

model_object_init:
  class_to_init: models.pytorch.pt_cnn.pt_cnn.PyTorchCNN

network_object_init:
  defaults_file: defaults/network.yaml
