# Copyright (C) 2020 Intel Corporation
# Licensed subject to Collaboration Agreement dated February 28th, 2020 between Intel Corporation and Trustees of the University of Pennsylvania.

# Compose an FL plan in JSON/YAML.
# The plan is consumed by bin/run_simulation_from_flplan.py,
# bin/run_aggregator_from_flplan, bin/run_collaborator_from_flplan, and
# bin/create_initial_weights_file_from_plan.py

# Note the use of yaml anchors and aliases in order to enforce dependencies
# across portions of the config:
# The anochor '&' assigns a name to a piece of the config
# The alias '*' references an achor 

# values for first level keys: model, aggregator, and collaborator
# pass in the generic kwargs for those constructors
# (ex. collaborator id will be collaborator specific)

# values for first level keys: model and data pass in the generic
# kwargs for get_model and get_data functions

# values for the first level key: hostnames is used in the creation of the public
# key infrastructure

# The model version is used to validate model updates
# Aggregator, collaborator, and fed ids (as well as model version) are currently
# used to validate message headers. Collaborator ids are also
# used for identifying the data folder of each collaborator
# (using the local_data_config yaml file)

aggregator:
  defaults_file: defaults/aggregator_test_mode_whitelist.yaml
  rounds_to_train: 10
  col_ids:
    - 'col_0'
    - 'col_1'
    - 'col_2'
    - 'col_3'
    - 'col_4'
    - 'col_5'
    - 'col_6'
    - 'col_7'
    - 'col_8'
    - 'col_9'
  init_model_fname: keras_cnn_mnist_init.pbuf
  latest_model_fname: keras_cnn_mnist_latest.pbuf
  best_model_fname: keras_cnn_mnist_best.pbuf

compression_pipeline:
  module_name: tfedlrn.tensor_transformation_pipelines
  class_name: SKCPipeline
  p_sparsity: 0.01
  n_clusters: 6

model:
  module_name: models.tensorflow.keras_cnn.keras_cnn
  class_name: KerasCNN

collaborator:
  defaults_file: defaults/collaborator.yaml

network:
  defaults_file: defaults/network.yaml

data:
  defaults_file: defaults/data_tf_mnist.yaml
  nb_collaborators: 10
  batch_size: 256
